### ISSUE TITLE
日记 YAML 区：创建日期、前后日期、往年今日

### ISSUE THREAD

**Issue by KrDw9ec4** [KrDw9ec4/flomo-diary-example#3]
保存创建日期，匹配生成前后日期，往年今日。

```yaml
---
created: 2023-09-17T22:24:43
Recently:
  - "[[2023-09-16]]"
  - "[[2023-09-18]]"
Today:
  - "[[2021-09-17]]"
---
```

// *以 `2023-09-17.md` 作为示例*
