### ISSUE TITLE
`Key:: Value` 识别：生成 Properties

### ISSUE THREAD

**Issue by KrDw9ec4** [KrDw9ec4/flomo-diary-example#8]
在 flomo 记录时使用 `Key:: Value` 的形式，等汇总时将其更改格式放入 YAML 区。

也支持将标签放入 YAML 区。

**Flomo**：

```text
FRM:: 张三，李四，王五
tags:: #Copy #Resourse #Technology
```

**Obsidian**：

```yaml
---
FRM: 
  - 张三
  - 李四
  - 王五
tags: 
  - Copy
  - Resourse
  - Technology
---
```

// *FRM:: Friend Relationship Management*
